/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CICD.schelude.project.jenkins.app;

import CICD.schelude.project.jenkins.list.LinkedList;

import static CICD.schelude.project.jenkins.utilities.StringUtils.join;
import static CICD.schelude.project.jenkins.utilities.StringUtils.split;
import static CICD.schelude.project.jenkins.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
