/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CICD.schelude.project.jenkins.app;

class MessageUtils {
    public static String getMessage() {
        return "Project CICD";
    }
}
